<?php
define( 'TWITTER_ACCESS_TOKEN', '2909021905-14UJRjbntbTPA9blKQxmFePGmBYiwfoEoWBkBx1' );
define( 'TWITTER_ACCESS_TOKEN_SECRET', '6Jk8xbXPKqNhyfnWixpGMEFf8PBA2hCytUrBDZZNPbQpR' );
define( 'TWITTER_CONSUMER_KEY', 'ahYCnqUamtJqivLopAaSqfoQk' );
define( 'TWITTER_CONSUMER_SECRET', 'NqmdCzPgzFQu52CCWhsj0bQwanquFpN7ktvrUSrD4fGTmixTZX' );
